Repository openwisp/openwisp-monitoring, pull requests merged in 2020-08, with the labels that each got.

#123 [feature] Add a check which inspects device configuration status periodically
  README.rst
  openwisp_monitoring/check/apps.py
  openwisp_monitoring/check/base/models.py
  openwisp_monitoring/check/classes/__init__.py
  openwisp_monitoring/check/classes/base.py
  openwisp_monitoring/check/classes/config_applied.py
  openwisp_monitoring/check/migrations/0005_create_config_applied.py
  openwisp_monitoring/check/settings.py
  openwisp_monitoring/check/tasks.py
  openwisp_monitoring/check/tests/test_models.py
  openwisp_monitoring/check/tests/test_ping.py
  openwisp_monitoring/db/backends/influxdb/client.py
  openwisp_monitoring/db/backends/influxdb/tests.py
  openwisp_monitoring/device/apps.py
  openwisp_monitoring/device/tests/test_models.py
  openwisp_monitoring/monitoring/base/models.py
  openwisp_monitoring/monitoring/metrics.py
  requirements-test.txt
Labels: enhancement, influxdb

#183 [feature] Added interface information
  README.rst
  openwisp_monitoring/device/schema.py
  openwisp_monitoring/device/templates/admin/config/device/change_form.html
  openwisp_monitoring/device/tests/__init__.py
  openwisp_monitoring/device/tests/test_admin.py
  openwisp_monitoring/device/tests/test_api.py
Labels: enhancement

#186 [tests] Added support for read_redirect view in notification tests
  openwisp_monitoring/device/tests/test_device_notifications.py
  openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py
Labels: bug

#187 Ignore connection timed out errors
  openwisp_monitoring/device/apps.py
  openwisp_monitoring/device/tests/test_models.py
Labels: enhancement

#192 [celery] Make tasks resilient to failures #181
  openwisp_monitoring/check/tasks.py
  openwisp_monitoring/check/tests/test_utils.py
  openwisp_monitoring/device/tasks.py
  openwisp_monitoring/device/tests/test_models.py
Labels: enhancement

#190 [timeseries] Make metric collection resilient to failures #166
  README.rst
  openwisp_monitoring/db/backends/influxdb/client.py
  openwisp_monitoring/db/backends/influxdb/exception.py
  openwisp_monitoring/db/backends/influxdb/tests.py
  openwisp_monitoring/db/exceptions.py
  openwisp_monitoring/device/apps.py
  openwisp_monitoring/device/base/models.py
  openwisp_monitoring/device/tests/test_models.py
  openwisp_monitoring/device/tests/test_recovery.py
  openwisp_monitoring/device/utils.py
  openwisp_monitoring/monitoring/base/models.py
  openwisp_monitoring/monitoring/settings.py
  openwisp_monitoring/monitoring/tasks.py
Labels: enhancement

#193 [refactor] Load BaseDevice using swappable
  openwisp_monitoring/device/models.py
  openwisp_monitoring/device/utils.py
  tests/openwisp2/sample_device_monitoring/models.py
Labels: enhancement

#196 Flat json widget
  tests/openwisp2/settings.py
Labels: enhancement

#185 [enhancement] Add way to specify global defaults
  README.rst
  openwisp_monitoring/check/classes/config_applied.py
  openwisp_monitoring/check/classes/ping.py
  openwisp_monitoring/check/settings.py
  openwisp_monitoring/db/backends/influxdb/tests.py
  openwisp_monitoring/device/admin.py
  openwisp_monitoring/device/api/views.py
  openwisp_monitoring/device/apps.py
  openwisp_monitoring/device/settings.py
  openwisp_monitoring/device/tests/test_models.py
  openwisp_monitoring/monitoring/admin.py
  openwisp_monitoring/monitoring/apps.py
  openwisp_monitoring/monitoring/base/models.py
  openwisp_monitoring/monitoring/charts.py
  openwisp_monitoring/monitoring/configuration.py
  openwisp_monitoring/monitoring/metrics.py
  openwisp_monitoring/monitoring/migrations/0006_add_configuration.py
  openwisp_monitoring/monitoring/migrations/0013_create_chart_alertsettings.py
  openwisp_monitoring/monitoring/migrations/0016_metric_configuration.py
  openwisp_monitoring/monitoring/migrations/0019_rename_alertsettings_fields.py
  openwisp_monitoring/monitoring/migrations/0020_make_alertsettings_fields_null.py
  openwisp_monitoring/monitoring/tests/__init__.py
  openwisp_monitoring/monitoring/tests/test_admin.py
  openwisp_monitoring/monitoring/tests/test_charts.py
  openwisp_monitoring/monitoring/tests/test_configuration.py
  openwisp_monitoring/monitoring/tests/test_models.py
  openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py
  tests/openwisp2/sample_monitoring/migrations/0001_initial.py
  tests/openwisp2/sample_monitoring/tests.py
  tests/openwisp2/settings.py
Labels: enhancement

#200 [chores] Update docs for #133
  README.rst
Labels: documentation

#201 [ux] Help user to find out what's wrong #172
  openwisp_monitoring/device/admin.py
  openwisp_monitoring/device/static/monitoring/css/monitoring.css
  openwisp_monitoring/device/tests/test_admin.py
Labels: enhancement

#213 Issues/212 health checks
  openwisp_monitoring/device/admin.py
  openwisp_monitoring/device/tests/test_admin.py
Labels: bug

#222 [fix] AlertSettings tolerance field should not have any default value
  install-dev.sh
  openwisp_monitoring/monitoring/base/models.py
  openwisp_monitoring/monitoring/migrations/0023_alert_settings_tolerance_remove_default.py
  openwisp_monitoring/monitoring/tests/test_models.py
  tests/openwisp2/sample_monitoring/migrations/0001_initial.py
Labels: bug

#220 [fix] Fixed tolerance to be checked in minutes and not seconds #219
  openwisp_monitoring/monitoring/base/models.py
  openwisp_monitoring/monitoring/tests/test_models.py
Labels: bug
