Repository openwisp/openwisp-monitoring, pull requests merged in 2020-07, with the labels that each got.

#147 [fix] Fixed broken chart js in metric admin change form #110
  openwisp_monitoring/monitoring/base/models.py
  openwisp_monitoring/monitoring/templates/admin/chart_inline.html
  openwisp_monitoring/monitoring/tests/test_charts.py
Labels: bug

#92 [docs] Document metrics stored in influxdb #81
  README.rst
  docs/cpu-load.png
  docs/device-status-1.png
  docs/device-status-2.png
  docs/device-status-3.png
  docs/device-status-4.png
  docs/disk-usage.png
  docs/memory.png
  docs/packet-loss.png
  docs/rtt.png
  docs/traffic.png
  docs/uptime.png
  docs/wifi-clients.png
Labels: documentation

#150 [feature] Add an Alert Settings section in device admin #52
  openwisp_monitoring/device/admin.py
  openwisp_monitoring/device/static/monitoring/css/monitoring.css
  openwisp_monitoring/device/static/monitoring/js/alertsettings_inline.js
  openwisp_monitoring/device/tests/test_admin.py
  openwisp_monitoring/monitoring/admin.py
  openwisp_monitoring/monitoring/base/models.py
  openwisp_monitoring/monitoring/migrations/0018_alertsettings_is_active.py
  openwisp_monitoring/monitoring/tests/test_monitoring_notifications.py
  requirements.txt
  tests/openwisp2/sample_monitoring/admin.py
  tests/openwisp2/sample_monitoring/migrations/0001_initial.py
  tests/openwisp2/settings.py
Labels: enhancement

#176 [fix] Avoid register_chart, unregister chart import while apps are being loaded
  README.rst
  openwisp_monitoring/monitoring/__init__.py
  openwisp_monitoring/monitoring/tests/__init__.py
Labels: bug

#178 Issues/177 bugged monitoring.0017 migration
  openwisp_monitoring/monitoring/migrations/0017_merge_traffic_metrics_and_fill_metric_config.py
Labels: bug

#179 [tests] Added geo_routes from controller
  tests/openwisp2/routing.py
Labels: enhancement
