Repository openwisp/openwisp-monitoring, pull requests merged in 2020-09, with the labels that each got.

#227 [deps] Upgrade InfluxDB python library to 5.3 #191
  openwisp_monitoring/device/tests/test_api.py
  requirements.txt
Labels: blocked, influxdb

#232 Updated requirements.txt
  requirements.txt
Labels: enhancement

#235 [fix] Config Applied checks would be skipped when device config status is errored #195
  openwisp_monitoring/check/classes/config_applied.py
  openwisp_monitoring/check/tests/test_models.py
  openwisp_monitoring/monitoring/base/models.py
Labels: bug
